services:
  backend:
    build: ./backend
    environment:
      PORT: 3001
      MONERO_NODE_1_HOST: ${MONERO_NODE_1_HOST:-monero_node_1}
      MONERO_NODE_1_PORT: ${MONERO_NODE_1_PORT:-18081}
      MONERO_NODE_1_USER: ${MONERO_NODE_1_USER:-}
      MONERO_NODE_1_PASS: ${MONERO_NODE_1_PASS:-}
      MONERO_NODE_1_TLS:  ${MONERO_NODE_1_TLS:-false}
      MONERO_NODE_2_HOST: ${MONERO_NODE_2_HOST:-}
      MONERO_NODE_2_PORT: ${MONERO_NODE_2_PORT:-18081}
      MONERO_NODE_2_USER: ${MONERO_NODE_2_USER:-}
      MONERO_NODE_2_PASS: ${MONERO_NODE_2_PASS:-}
      MONERO_NODE_2_TLS:  ${MONERO_NODE_2_TLS:-false}
      MONERO_NODE_3_HOST: ${MONERO_NODE_3_HOST:-}
      MONERO_NODE_3_PORT: ${MONERO_NODE_3_PORT:-18081}
      MONERO_NODE_3_USER: ${MONERO_NODE_3_USER:-}
      MONERO_NODE_3_PASS: ${MONERO_NODE_3_PASS:-}
      MONERO_NODE_3_TLS:  ${MONERO_NODE_3_TLS:-false}
    networks:
      - default
      - monero_1_default
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
  monero_1_default:
    external: true
